### ISSUE TITLE
[bug] Item Duplication

### ISSUE THREAD

**Issue by FrozenBeard** [eirikh1996/StructureBoxes#10]
Quite a big one here, Related to #8 
Players can just get infinite blocks by placing down a structure, mining the blocks and then undoing it rinse and repeat for infinite blocks, this is a major flaw on a survival. 
It doesn't help that the timers not working for being able to do an undo.

As you are already checking an area before pasting to make sure there is room, can you check for if the player breaks any blocks in this area that they are pasting into, then you can cancel the undo if they break any blocks.

**Comment by eirikh1996** [comment]
Fixed in 4621c48519482afe149ab32eaca09165e2861cba
