### ISSUE TITLE
This'a not a workt

### ISSUE THREAD

**Issue by successed** [eirikh1996/StructureBoxes#12]
It doesn't stick anything, it keeps failing.
![Screenshot_5](https://user-images.githubusercontent.com/13768414/74794122-6c7e1200-52d3-11ea-8b0d-db7e13e28a86.png)

Server version 1.8.8

Worldedit version : worldedit-bukkit-6.1.9

**Comment by eirikh1996** [comment]
This is not a bug. This is due to where you did //copy from when you save the schematic. If familiar with using WorldEdit, when copying a structure, it will store the player's current position as the origin point. The relative location of the origin is also where it will paste fromm when you paste it into the world. StructureBoxes does the same thing when loading and pasting the schematics: The placement location will also work as an origin point from where it will paste the structure.

**Comment by successed** [comment]
> This is not a bug. This is due to where you did //copy from when you save the schematic. If familiar with using WorldEdit, when copying a structure, it will store the player's current position as the origin point. The relative location of the origin is also where it will paste fromm when you paste it into the world. StructureBoxes does the same thing when loading and pasting the schematics: The placement location will also work as an origin point from where it will paste the structure.

The schematic is only a 4x4 stone block.

**Comment by eirikh1996** [comment]
> > This is not a bug. This is due to where you did //copy from when you save the schematic. If familiar with using WorldEdit, when copying a structure, it will store the player's current position as the origin point. The relative location of the origin is also where it will paste fromm when you paste it into the world. StructureBoxes does the same thing when loading and pasting the schematics: The placement location will also work as an origin point from where it will paste the structure.
> 
> The schematic is only a 4x4 stone block. This'a real bug, Just try this.
> ![Screenshot_6](https://user-images.githubusercontent.com/13768414/74880727-def6fc80-537c-11ea-8a52-7222c9f9c583.png)

Are you standing on the grass surface when you paste it? Cause Structure Boxes does have a free space check which checks if every block in the world where the structure goes is either air or blocks the plugin will ignore. The latter is configurable: Go to config.yml, locate the field called "Blocks to ignore", and try adding grass and/or dirt to it and see if it helps

**Comment by successed** [comment]
> > > This is not a bug. This is due to where you did //copy from when you save the schematic. If familiar with using WorldEdit, when copying a structure, it will store the player's current position as the origin point. The relative location of the origin is also where it will paste fromm when you paste it into the world. StructureBoxes does the same thing when loading and pasting the schematics: The placement location will also work as an origin point from where it will paste the structure.
> > 
> > 
> > The schematic is only a 4x4 stone block. This'a real bug, Just try this.
> > ![Screenshot_6](https://user-images.githubusercontent.com/13768414/74880727-def6fc80-537c-11ea-8a52-7222c9f9c583.png)
> 
> Are you standing on the grass surface when you paste it? Cause Structure Boxes does have a free space check which checks if every block in the world where the structure goes is either air or blocks the plugin will ignore. The latter is configurable: Go to config.yml, locate the field called "Blocks to ignore", and try adding grass and/or dirt to it and see if it helps

Okay, work now. And i need asyncworldedit and fawe support
