### ISSUE TITLE
[Bug] When using FAWE when you create a schematic your schematic is saved in a folder with your UUID

### ISSUE THREAD

**Issue by FrozenBeard** [eirikh1996/StructureBoxes#7]
StructureBoxes will not be able to find the schematic if you save a schematic with FAWE as FAWE saves schematics in a folder per user UUID, you have to copy the schematic into the root directory.

**Comment by eirikh1996** [comment]
Are you intending to allow players on a creative server to create structure boxes?

**Comment by FrozenBeard** [comment]
@eirikh1996 no!
